"""Add monthly_usage and usage_reset_date columns

Revision ID: 96effe6c36fe
Revises: 
Create Date: 2025-03-25 23:15:14.243445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96effe6c36fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_usage', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usage_reset_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usage_reset_date')
    op.drop_column('users', 'monthly_usage')
    # ### end Alembic commands ###
